export const size = {
    xhuge: 52,
    huge: 50,
    xxxtitle: 38,
    xxtitle: 36,
    xtitle: 34,
    title: 32,
    h1: 30,
    h2: 28,
    h3: 26,
    h4: 25,
    h5: 24,
    h6: 22,
    xxlarge: 20,
    xlarge: 19,
    large: 18,
    medium: 17,
    normal: 16,
    small: 15,
    xsmall: 14,
    xxsmall: 13,
    tiny: 12,
    xtiny: 11,
    xxtiny: 10,
    xxxtiny: 9,
    xxxxtiny: 8,
  };
  
  export const appRadius = {
    buttonRadius: 25,
    boxRadius: 18,
  };
  
  export const family = {
    comorfaBold: 'comfortaBold',
    comorfaLight: 'comfortaBold',
    comorfaRegular: 'comfortaRegular',
    OpenSans_Bold: 'OpenSans-Bold',
    OpenSans_BoldItalic: 'OpenSans-BoldItalic',
    OpenSans_ExtraBold: 'OpenSans-ExtraBold',
    OpenSans_ExtraBoldItalic: 'OpenSans-ExtraBoldItalic',
    OpenSans_Italic: 'OpenSans-Italic',
    OpenSans_Light: 'OpenSans-Light',
    OpenSans_LightItalic: 'OpenSans-LightItalic',
    OpenSans_Medium: 'OpenSans-Medium',
    OpenSans_MediumItalic: 'OpenSans-MediumItalic',
    OpenSans_Regular: 'OpenSans-Regular',
    OpenSans_SemiBold: 'OpenSans-SemiBold',
    OpenSans_SemiBoldItalic: 'OpenSans-SemiBoldItalic',
    // English Fonts
    Poppins_ThinItalic: 'Poppins-ThinItalic',
    Poppins_Thin: 'Poppins-Thin',
    Poppins_SemiBoldItalic: 'Poppins-SemiBoldItalic',
    Poppins_SemiBold: 'Poppins-SemiBold',
    Poppins_Regular: 'Poppins-Regular',
    Poppins_MediumItalic: 'Poppins-MediumItalic',
    Poppins_Medium: 'Poppins-Medium',
    Poppins_LightItalic: 'Poppins-LightItalic',
    Poppins_Light: 'Poppins-Light',
    Poppins_Italic: 'Poppins-Italic',
    Poppins_ExtraLightItalic: 'Poppins-ExtraLightItalic',
    Poppins_ExtraLight: 'Poppins-ExtraLight',
    Poppins_ExtraBoldItalic: 'Poppins-ExtraBoldItalic',
    Poppins_ExtraBold: 'Poppins-ExtraBold',
    Poppins_BoldItalic: 'Poppins-BoldItalic',
    Poppins_Bold: 'Poppins-Bold',
    Poppins_BlackItalic: 'Poppins-BlackItalic',
    Poppins_Black: 'Poppins-Black',
  
    Montserrat_Black: 'Montserrat-Black',
    Montserrat_BlackItalic: 'Montserrat-BlackItalic',
    Montserrat_Bold: 'Montserrat-Bold',
    Montserrat_BoldItalic: 'Montserrat-BoldItalic',
    Montserrat_ExtraBold: 'Montserrat-ExtraBold',
    Montserrat_ExtraBoldItalic: 'Montserrat-ExtraBoldItalic',
    Montserrat_ExtraLight: 'Montserrat-ExtraLight',
    Montserrat_ExtraLightItalic: 'Montserrat-ExtraLightItalic',
    Montserrat_Italic: 'Montserrat-Italic',
    Montserrat_Light: 'Montserrat-Light',
    Montserrat_LightItalic: 'Montserrat-LightItalic',
    Montserrat_Medium: 'Montserrat-Medium',
    Montserrat_MediumItalic: 'Montserrat-MediumItalic',
    Montserrat_Regular: 'Montserrat-Regular',
    Montserrat_SemiBold: 'Montserrat-SemiBold',
    Montserrat_SemiBoldItalic: 'Montserrat-SemiBoldItalic',
    Montserrat_Thin: 'Montserrat-Thin',
    Montserrat_ThinItalic: 'Montserrat-ThinItalic',
  
    Inter_Black: 'Inter-Black',
    Inter_Bold: 'Inter-Bold',
    Inter_ExtraBold: 'Inter-ExtraBold',
    Inter_ExtraLight: 'Inter-ExtraLight',
    Inter_Light: 'Inter-Light',
    Inter_Medium: 'Inter-Medium',
    Inter_Regular: 'Inter-Regular',
    Inter_SemiBold: 'Inter-SemiBold',
    Inter_Thin: 'Inter-Thin',
  
    Karla_Bold: 'Karla-Bold',
    Karla_BoldItalic: 'Karla-BoldItalic',
    Karla_ExtraBold: 'Karla-ExtraBold',
    Karla_ExtraBoldItalic: 'Karla-ExtraBoldItalic',
    Karla_ExtraLight: 'Karla-ExtraLight',
    Karla_ExtraLightItalic: 'Karla-ExtraLightItalic',
    Karla_Light: 'Karla-Light',
    Karla_Italic: 'Karla-Italic',
    Karla_LightItalic: 'Karla-LightItalic',
    Karla_Medium: 'Karla-Medium',
    Karla_MediumItalic: 'Karla-MediumItalic',
    Karla_Regular: 'Karla-Regular',
    Karla_SemiBold: 'Karla-SemiBold',
    Karla_SemiBoldItalic: 'Karla-SemiBoldItalic',
  };
  